# Generated by Django 4.2.4 on 2023-08-08 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0004_prescription_dosage_time_prescription_duration_and_more"),
        ("diseases", "0002_remove_disease_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="medicine",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="medicines.medicine"),
        ),
    ]
