# Generated by Django 4.2.4 on 2023-08-11 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diseases", "0003_disease_medicine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disease",
            name="medicine",
        ),
    ]
