# Generated by Django 4.2.4 on 2023-08-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0001_initial"),
        ("diseases", "0001_initial"),
        ("users", "0002_user_age_user_disease_user_first_name_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="disease",
            field=models.ManyToManyField(related_name="users", to="diseases.disease"),
        ),
        migrations.AlterField(
            model_name="user",
            name="medicine",
            field=models.ManyToManyField(related_name="users", to="medicines.medicine"),
        ),
    ]
