# Generated by Django 4.2.4 on 2023-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0001_initial"),
        ("diseases", "0001_initial"),
        ("users", "0003_alter_user_disease_alter_user_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="disease",
            field=models.ManyToManyField(blank=True, related_name="users", to="diseases.disease"),
        ),
        migrations.AlterField(
            model_name="user",
            name="medicine",
            field=models.ManyToManyField(blank=True, related_name="users", to="medicines.medicine"),
        ),
    ]
