# Generated by Django 4.2.4 on 2023-08-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_age_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A Positive"),
                    ("A-", "A Negative"),
                    ("B+", "B Positive"),
                    ("B-", "B Negative"),
                    ("AB+", "AB Positive"),
                    ("AB-", "AB Negative"),
                    ("O+", "O Positive"),
                    ("O-", "O Negative"),
                ],
                max_length=255,
            ),
        ),
    ]
