# Generated by Django 4.2.4 on 2023-08-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacies", "0001_initial"),
        ("users", "0006_user_blood_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="regular_pharmacy",
            field=models.ManyToManyField(related_name="users", to="pharmacies.pharmacy"),
        ),
    ]
