# Generated by Django 4.2.4 on 2023-08-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacies", "0001_initial"),
        ("users", "0007_user_regular_pharmacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="regular_pharmacy",
            field=models.ManyToManyField(blank=True, related_name="users", to="pharmacies.pharmacy"),
        ),
    ]
