# Generated by Django 4.2.4 on 2023-08-18 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_user_widget"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="widget",
        ),
    ]
