# Generated by Django 4.2.4 on 2023-08-18 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_widget"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Widget",
        ),
    ]
