# Generated by Django 4.2.4 on 2023-08-22 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alarm",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dosage",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None
            ),
        ),
    ]
