# Generated by Django 4.2.4 on 2023-08-18 10:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("widgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="text",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None),
        ),
    ]
