# Generated by Django 4.2.4 on 2023-08-03 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medicines", "0002_remove_medicine_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="prescription_date",
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prescription_date", models.DateField()),
                ("medicine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="medicines.medicine")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
