# Generated by Django 4.2.4 on 2023-08-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0003_remove_medicine_prescription_date_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="dosage_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="hospital",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
