# Generated by Django 4.2.4 on 2023-08-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0004_prescription_dosage_time_prescription_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="picture",
            field=models.ImageField(null=True, upload_to="prescription_picture/"),
        ),
    ]
