# Generated by Django 4.2.4 on 2023-08-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0005_prescription_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="prescription_date",
            field=models.DateField(null=True),
        ),
    ]
