# Generated by Django 4.2.4 on 2023-08-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0006_alter_prescription_prescription_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="atpnQesitm",
            field=models.CharField(max_length=10485760, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="atpnWarnQesitm",
            field=models.CharField(max_length=10485760, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="depositMethodQesitm",
            field=models.CharField(max_length=10485760, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="efcyQesitm",
            field=models.CharField(max_length=10485760, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="entpName",
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="intrcQesitm",
            field=models.CharField(max_length=10485760, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="seQesitm",
            field=models.CharField(max_length=10485760, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="useMethodQesitm",
            field=models.CharField(max_length=10485760, null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="image",
            field=models.ImageField(null=True, upload_to="media/medicine_pictures"),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
