# Generated by Django 4.2.4 on 2023-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0007_medicine_atpnqesitm_medicine_atpnwarnqesitm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DosageTime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="dosage_time",
        ),
        migrations.AlterField(
            model_name="medicine",
            name="image",
            field=models.ImageField(null=True, upload_to="medicine_pictures/"),
        ),
        migrations.AddField(
            model_name="prescription",
            name="dosage_times",
            field=models.ManyToManyField(to="medicines.dosagetime"),
        ),
    ]
