# Generated by Django 4.2.4 on 2023-08-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0008_dosagetime_remove_prescription_dosage_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="itemSeq",
            field=models.IntegerField(null=True),
        ),
    ]
