# Generated by Django 4.2.4 on 2023-08-14 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0009_medicine_itemseq"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="picture",
            new_name="image",
        ),
    ]
