# Generated by Django 4.2.4 on 2023-08-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0010_rename_picture_prescription_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="medicine_pictures/"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="dosage_times",
            field=models.ManyToManyField(blank=True, null=True, to="medicines.dosagetime"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="prescription_picture/"),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="medicine",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="medicines.medicine"
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="prescription_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
