# Generated by Django 4.2.4 on 2023-08-16 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medicines", "0013_alter_medicine_image_alter_prescription_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="prescriptions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
