# Generated by Django 4.2.4 on 2023-08-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0015_remove_prescription_medicine_prescription_medicine"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemSeq",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="medicine",
            name="eng_ingredient",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="ingredient",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="atpnQesitm",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="atpnWarnQesitm",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="depositMethodQesitm",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="efcyQesitm",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="intrcQesitm",
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="itemSeq",
        ),
        migrations.AlterField(
            model_name="medicine",
            name="seQesitm",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="useMethodQesitm",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="itemSeq",
            field=models.ManyToManyField(blank=True, to="medicines.itemseq"),
        ),
    ]
