# Generated by Django 4.2.4 on 2023-08-22 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0016_itemseq_medicine_eng_ingredient_medicine_ingredient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="atpnWarnQesitm",
        ),
    ]
