# Generated by Django 4.2.4 on 2023-08-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0017_remove_medicine_atpnwarnqesitm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemseq",
            name="number",
            field=models.BigIntegerField(),
        ),
    ]
