# Generated by Django 4.2.4 on 2023-08-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0019_contraindication"),
    ]

    operations = [
        migrations.AddField(
            model_name="contraindication",
            name="detail",
            field=models.TextField(null=True),
        ),
    ]
