# Generated by Django 4.2.4 on 2023-08-22 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0021_alter_medicine_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="dosage_times",
        ),
        migrations.DeleteModel(
            name="DosageTime",
        ),
    ]
