# Generated by Django 4.2.4 on 2023-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0022_remove_prescription_dosage_times_delete_dosagetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("image_hash", models.CharField(max_length=64)),
                ("image", models.ImageField(upload_to="search_images/")),
            ],
        ),
    ]
