# Generated by Django 4.2.4 on 2023-08-24 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0024_medicineimage_prescription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MedicineImage",
        ),
    ]
