# Generated by Django 4.2.4 on 2023-08-24 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacies", "0001_initial"),
        ("medicines", "0025_delete_medicineimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="pharmacies.pharmacy",
            ),
        ),
    ]
