# Generated by Django 4.2.4 on 2023-08-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicines", "0026_alter_prescription_hospital"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="ocr_data",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
